[tool.poetry]
name = "expats"
version = "0.1.0"
description = ""
authors = ["Gustavo Tempel <gtempel@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
